version: '3.8'

services:
  backend:
    build: ./backend
    network_mode: host  # Use host networking
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build: ./frontend
    network_mode: host  # Use host networking
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: unless-stopped
